// ReSharper disable InconsistentNaming

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DISourceGenerator;

[Generator]
public class DIAutowireGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. DeclareDIComponentType Phase
        var componentTypeProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            "DIAutowire.Attributes.Interface.DeclareDIComponentTypeAttribute",
            (_, _) => true,
            (ctx, _) =>
            {
                var names = new List<string>();
                foreach (var attr in ctx.Attributes)
                {
                    if (attr.ConstructorArguments.Length <= 0)
                        continue;

                    var name = attr.ConstructorArguments[0].Value?.ToString();
                    if (name is { Length: > 0 })
                        names.Add(name);
                }

                return names;
            }
        ).SelectMany((names, _) => names);

        context.RegisterSourceOutput(componentTypeProvider, (ctx, name) =>
        {
            var code = $$"""
                         // <auto-generated/>
                         using DIAutowire.Attributes.Interface;

                         namespace DIAutowire.Attributes.Interface;

                         public class {{name}} : DIComponentAttribute { }

                         """;
            ctx.AddSource($"{name}Attribute.g.cs", SourceText.From(code, Encoding.UTF8));
        });

        // 2. Interface Generation Phase
        var classDeclarations = context.SyntaxProvider.CreateSyntaxProvider(
            (s, _) => s is ClassDeclarationSyntax,
            (ctx, _) =>
            {
                var classSyntax = (ClassDeclarationSyntax)ctx.Node;
                var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classSyntax);
                if (classSymbol == null) return null;

                var hasDiComponent = false;
                foreach (var attr in classSymbol.GetAttributes())
                {
                    if (attr.AttributeClass == null || !InheritsFrom(attr.AttributeClass,
                            "DIAutowire.Attributes.Interface.DIComponentAttribute"))
                        continue;
                    hasDiComponent = true;
                    break;
                }

                // Fallback for generated attributes in the same compilation:
                // scan for DeclareDIComponentType("X") to build the set of valid names
                if (!hasDiComponent)
                {
                    var declaredNames = new HashSet<string>();
                    foreach (var tree in ctx.SemanticModel.Compilation.SyntaxTrees)
                    foreach (var attrSyntax in tree.GetRoot().DescendantNodes().OfType<AttributeSyntax>())
                    {
                        var attrName = attrSyntax.Name.ToString();
                        if (attrName is not ("DeclareDIComponentType" or "DeclareDIComponentTypeAttribute"))
                            continue;
                        if (attrSyntax.ArgumentList?.Arguments.Count > 0 &&
                            attrSyntax.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax literal)
                            declaredNames.Add(literal.Token.ValueText);
                    }

                    // Also always include the built-in DIComponent
                    declaredNames.Add("DIComponent");

                    foreach (var attrList in classSyntax.AttributeLists)
                    foreach (var name in attrList.Attributes.Select(attr => attr.Name.ToString()))
                    {
                        if (!declaredNames.Contains(name))
                            continue;
                        hasDiComponent = true;
                        break;
                    }
                }

                if (!hasDiComponent)
                    return null;

                // Extract comments
                var docs = classSyntax
                    .GetLeadingTrivia()
                    .FirstOrDefault(t =>
                        t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) ||
                        t.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia));
                var docString = docs != default ? docs.ToFullString() : string.Empty;

                // Extract public members
                var publicMembers = new List<string>();
                foreach (var member in classSyntax.Members)
                    switch (member)
                    {
                        case MethodDeclarationSyntax method when method.Modifiers.Any(SyntaxKind.PublicKeyword) &&
                                                                 !method.Modifiers.Any(SyntaxKind.StaticKeyword):
                        {
                            var modifiers = method.Modifiers.Where(m =>
                                !m.IsKind(SyntaxKind.PublicKeyword) && !m.IsKind(SyntaxKind.AsyncKeyword) &&
                                !m.IsKind(SyntaxKind.OverrideKeyword) && !m.IsKind(SyntaxKind.VirtualKeyword));
                            var newMethod = method.WithModifiers(SyntaxFactory.TokenList(modifiers))
                                .WithAttributeLists(SyntaxFactory.List<AttributeListSyntax>())
                                .WithBody(null).WithExpressionBody(null)
                                .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken));

                            var memberDocs = method.GetLeadingTrivia().FirstOrDefault(t =>
                                t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) ||
                                t.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia));
                            var memberDocString = memberDocs != default ? memberDocs.ToFullString() : string.Empty;

                            publicMembers.Add(memberDocString + newMethod.NormalizeWhitespace().ToFullString());
                            break;
                        }
                        case PropertyDeclarationSyntax prop when prop.Modifiers.Any(SyntaxKind.PublicKeyword) &&
                                                                 !prop.Modifiers.Any(SyntaxKind.StaticKeyword):
                        {
                            var modifiers = prop.Modifiers.Where(m =>
                                !m.IsKind(SyntaxKind.PublicKeyword) && !m.IsKind(SyntaxKind.OverrideKeyword) &&
                                !m.IsKind(SyntaxKind.VirtualKeyword));
                            var hasGet =
                                prop.AccessorList?.Accessors.Any(a => a.IsKind(SyntaxKind.GetAccessorDeclaration)) ??
                                prop.ExpressionBody != null;
                            var hasSet =
                                prop.AccessorList?.Accessors.Any(a => a.IsKind(SyntaxKind.SetAccessorDeclaration)) ??
                                false;

                            var accessors = new List<AccessorDeclarationSyntax>();
                            if (hasGet)
                                accessors.Add(SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                                    .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)));
                            if (hasSet)
                                accessors.Add(SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                                    .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)));

                            var newProp = prop.WithModifiers(SyntaxFactory.TokenList(modifiers))
                                .WithAttributeLists(SyntaxFactory.List<AttributeListSyntax>())
                                .WithAccessorList(SyntaxFactory.AccessorList(SyntaxFactory.List(accessors)))
                                .WithExpressionBody(null).WithInitializer(null).WithSemicolonToken(default);

                            var memberDocs = prop.GetLeadingTrivia().FirstOrDefault(t =>
                                t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) ||
                                t.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia));
                            var memberDocString = memberDocs != default ? memberDocs.ToFullString() : string.Empty;

                            publicMembers.Add(memberDocString + newProp.NormalizeWhitespace().ToFullString());
                            break;
                        }
                    }

                return new ClassGenerationInfo
                {
                    ClassName = classSymbol.Name,
                    NamespaceName = classSymbol.ContainingNamespace.ToDisplayString(),
                    IsPartial = classSyntax.Modifiers.Any(SyntaxKind.PartialKeyword),
                    DocComments = docString,
                    Members = publicMembers
                };
            }
        ).Where(x => x != null);

        context.RegisterSourceOutput(classDeclarations, (ctx, info) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"namespace {info!.NamespaceName};");
            sb.AppendLine();
            if (!string.IsNullOrWhiteSpace(info.DocComments)) sb.Append(info.DocComments);
            sb.AppendLine($"public interface I{info.ClassName}");
            sb.AppendLine("{");
            foreach (var member in info.Members) sb.AppendLine("    " + member.Replace("\n", "\n    "));
            sb.AppendLine("}");
            sb.AppendLine();
            if (info.IsPartial) sb.AppendLine($"public partial class {info.ClassName} : I{info.ClassName} {{ }}");

            ctx.AddSource($"I{info.ClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });

        // 3. Autowire Generation Phase
        var autowireClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
            "DIAutowire.Attributes.Implementation.AutowireAttribute",
            (node, _) => node is ClassDeclarationSyntax,
            (ctx, _) =>
            {
                var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                var attr = ctx.Attributes.First();
                var lifetime = 1; // Scoped by default

                // Inspect constructor arguments to get lifetime (1 = Scoped, 0 = Singleton, 2 = Transient)
                // ServiceLifetime enum: Singleton = 0, Scoped = 1, Transient = 2
                var implementationName = string.Empty;
                switch (attr.ConstructorArguments.Length)
                {
                    case > 0 when
                        (attr.ConstructorArguments[0].Type?.SpecialType == SpecialType.System_String):
                    {
                        implementationName = attr.ConstructorArguments[0].Value as string ?? string.Empty;
                        if (attr.ConstructorArguments.Length >= 2 &&
                            attr.ConstructorArguments[1].Type?.Name == "ServiceLifetime")
                            lifetime = (int)attr.ConstructorArguments[1].Value!;
                        break;
                    }
                    case >= 1 when
                        (attr.ConstructorArguments[0].Type?.Name == "ServiceLifetime"):
                        lifetime = (int)attr.ConstructorArguments[0].Value!;
                        break;
                }

                // Also check named arguments just in case
                foreach (var namedArg in attr.NamedArguments)
                {
                    switch (namedArg.Key)
                    {
                        case "ImplementationName" when
                            (namedArg.Value.Type?.SpecialType == SpecialType.System_String):
                            implementationName = namedArg.Value.Value as string ?? string.Empty;
                            break;
                        case "ImplementationLifetime" when (namedArg.Value.Type?.Name == "ServiceLifetime"):
                            lifetime = (int)namedArg.Value.Value!;
                            break;
                    }
                }

                // Check if the class also has a DIComponent attribute (or derivative)
                var hasDiComponent = classSymbol.GetAttributes().Any(a =>
                    a.AttributeClass != null && InheritsFrom(a.AttributeClass,
                        "DIAutowire.Attributes.Interface.DIComponentAttribute"));

                // Fallback for generated attributes in the same compilation
                if (!hasDiComponent)
                {
                    var declaredNames = new HashSet<string>();
                    foreach (var tree in ctx.SemanticModel.Compilation.SyntaxTrees)
                    foreach (var attrSyntax in tree.GetRoot().DescendantNodes().OfType<AttributeSyntax>())
                    {
                        var attrName = attrSyntax.Name.ToString();
                        if (attrName is not ("DeclareDIComponentType" or "DeclareDIComponentTypeAttribute"))
                            continue;
                        if (attrSyntax.ArgumentList?.Arguments.Count > 0 &&
                            attrSyntax.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax literal)
                            declaredNames.Add(literal.Token.ValueText);
                    }

                    declaredNames.Add("DIComponent");

                    var classSyntax = (ClassDeclarationSyntax)ctx.TargetNode;
                    foreach (var attrList in classSyntax.AttributeLists)
                    foreach (var name in attrList.Attributes.Select(a => a.Name.ToString()))
                    {
                        if (!declaredNames.Contains(name))
                            continue;
                        hasDiComponent = true;
                        break;
                    }
                }

                // Check if any implemented interfaces have [DIComponent] (or derivative)
                var diComponentInterfaces = new List<string>();
                if (!hasDiComponent)
                {
                    foreach (var iface in classSymbol.AllInterfaces)
                    {
                        var ifaceHasDiComponent = iface.GetAttributes().Any(a =>
                            a.AttributeClass != null && InheritsFrom(a.AttributeClass,
                                "DIAutowire.Attributes.Interface.DIComponentAttribute"));

                        // Fallback: check syntax-level attribute names for generated component types
                        if (!ifaceHasDiComponent)
                        {
                            var declaredNames = new HashSet<string>();
                            foreach (var tree in ctx.SemanticModel.Compilation.SyntaxTrees)
                            foreach (var attrSyntax in tree.GetRoot().DescendantNodes().OfType<AttributeSyntax>())
                            {
                                var attrName = attrSyntax.Name.ToString();
                                if (attrName is not ("DeclareDIComponentType" or "DeclareDIComponentTypeAttribute"))
                                    continue;
                                if (attrSyntax.ArgumentList?.Arguments.Count > 0 &&
                                    attrSyntax.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax literal)
                                    declaredNames.Add(literal.Token.ValueText);
                            }
                            declaredNames.Add("DIComponent");

                            foreach (var syntaxRef in iface.DeclaringSyntaxReferences)
                            {
                                if (syntaxRef.GetSyntax() is not InterfaceDeclarationSyntax ifaceSyntax)
                                    continue;
                                foreach (var attrList in ifaceSyntax.AttributeLists)
                                foreach (var name in attrList.Attributes.Select(a => a.Name.ToString()))
                                {
                                    if (declaredNames.Contains(name))
                                        ifaceHasDiComponent = true;
                                }
                            }
                        }

                        if (ifaceHasDiComponent)
                            diComponentInterfaces.Add(iface.ToDisplayString());
                    }
                }

                var ns = classSymbol.ContainingNamespace.ToDisplayString();
                return new AutowireInfo
                {
                    ClassName = classSymbol.Name, Namespace = ns, Lifetime = lifetime,
                    ImplementationName = implementationName, HasDiComponent = hasDiComponent,
                    DIComponentInterfaces = diComponentInterfaces
                };
            }
        ).Collect();

        context.RegisterSourceOutput(autowireClasses, (ctx, classes) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace DIAutowire.Extensions;");
            sb.AppendLine();
            sb.AppendLine("internal static class IServiceCollectionExtensions");
            sb.AppendLine("{");
            sb.AppendLine(
                "    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection DIAutowire(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            sb.AppendLine("    {");
            sb.AppendLine("        services.AddTransient(typeof(global::DIAutowire.Helpers.ServiceResolver<>));");

            foreach (var cls in classes)
            {
                var lifetimeStr = cls.Lifetime switch
                {
                    0 => "Singleton",
                    2 => "Transient",
                    _ => "Scoped"
                };
                if (cls.HasDiComponent)
                {
                    // Interface-based registration (class has DIComponent, so an interface is generated)
                    sb.AppendLine(
                        string.IsNullOrEmpty(cls.ImplementationName)
                            ? $"        services.Add{lifetimeStr}<global::{cls.Namespace}.I{cls.ClassName}, global::{cls.Namespace}.{cls.ClassName}>();"
                            : $"        services.AddKeyed{lifetimeStr}<global::{cls.Namespace}.I{cls.ClassName}, global::{cls.Namespace}.{cls.ClassName}>(\"{cls.ImplementationName}\");");
                }
                else if (cls.DIComponentInterfaces.Count > 0)
                {
                    // Registration against pre-existing interfaces that have [DIComponent]
                    foreach (var ifaceName in cls.DIComponentInterfaces)
                    {
                        sb.AppendLine(
                            string.IsNullOrEmpty(cls.ImplementationName)
                                ? $"        services.Add{lifetimeStr}<global::{ifaceName}, global::{cls.Namespace}.{cls.ClassName}>();"
                                : $"        services.AddKeyed{lifetimeStr}<global::{ifaceName}, global::{cls.Namespace}.{cls.ClassName}>(\"{cls.ImplementationName}\");");
                    }
                }
                else
                {
                    // Self-registration (class only has Autowire, no interface generation)
                    sb.AppendLine(
                        string.IsNullOrEmpty(cls.ImplementationName)
                            ? $"        services.Add{lifetimeStr}<global::{cls.Namespace}.{cls.ClassName}>();"
                            : $"        services.AddKeyed{lifetimeStr}<global::{cls.Namespace}.{cls.ClassName}>(\"{cls.ImplementationName}\");");
                }
            }

            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource("DIAutowireExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, string baseName)
    {
        var current = symbol;
        while (current != null)
        {
            if (current.ToDisplayString() == baseName) return true;
            current = current.BaseType;
        }

        return false;
    }

    private class ClassGenerationInfo
    {
        public string ClassName { get; set; } = string.Empty;
        public string NamespaceName { get; set; } = string.Empty;
        public bool IsPartial { get; set; }
        public string DocComments { get; set; } = string.Empty;
        public List<string> Members { get; set; } = [];
    }

    private class AutowireInfo
    {
        public string ClassName { get; set; } = string.Empty;
        public string Namespace { get; set; } = string.Empty;
        public int Lifetime { get; set; }
        public string ImplementationName { get; set; } = string.Empty;
        public bool HasDiComponent { get; set; }
        public List<string> DIComponentInterfaces { get; set; } = new List<string>();
    }
}